read_data_from_sql: True
rebatch: False
feature_scaling_factor: 10000
target_table:
profile_table:
factor_table:
campaign_table:
meeting_table:
num_mini_batch_per_batch: 10000
train_fraction: 0.6
validation_fraction: 0.2
