model_name: 'classifier_gru'
model_type: "classifier"
epoch: 100
batch_size: 48
num_class: 6
class_weight:
  - 0.02
  - 0.1
  - 0.1
  - 0.1
  - 0.25
  - 0.6
loss_recording_step: 50
model_hyperparameters:
  in_channels_profile: 68
  in_channels_campaign: 24
  in_channels_meeting: 9
  in_channels_action: 22
  # profile_hist_len: 12
  # out_channel_profile: 10
  hidden_size_profile: 30
  hidden_size_campaign: 10
  hidden_size_meeting: 5
  #kernel_size: 3
  dropout: 0.2
  out_channel: 6
training_parameters:
  lr: 0.0001
  momentum: 0.9
