prediction_table:
data_name: 'classifier_meet_only'
read_data_from_sql: False
create_prediction_table: False
prediction_action_vector:
  is_meeting:
  digital_priming:
  meeting_source:
  location: 
prediction_batches:
  - 0
  - 10000
batch_size: 64
rebatch: False